services:
  audiobookshelf-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.12.0
    container_name: abs-bot
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - logs:/app/logs

volumes:
  logs:
    driver: local